[package]
name = "paholib"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.0"
env_logger = "0.10.0"
tokio = { version = "1.26.0", features = ["full"] }
paho-mqtt = "0.12.0"

[dev-dependencies]
uuid = { version = "1.3.0", features = ["v4", "fast-rng"] }
futures = "0.3.27"
